# Mock data for backend development
# In production, this would be replaced with a real database

servers = [
    {
        "id": "srv-001",
        "name": "RAXUS-PROD-01",
        "ip": "10.0.1.10",
        "type": "linux",
        "os": "Ubuntu 22.04 LTS",
        "status": "online",
        "cpu": 42,
        "memory": 68,
        "disk": 55,
        "uptime": "45d 12h 32m",
        "location": "DC-Paris-01",
        "cores": 16,
        "ramTotal": 64,
        "lastChecked": "2 min ago",
    },
    {
        "id": "srv-002",
        "name": "RAXUS-PROD-02",
        "ip": "10.0.1.11",
        "type": "linux",
        "os": "CentOS 8",
        "status": "online",
        "cpu": 78,
        "memory": 82,
        "disk": 45,
        "uptime": "30d 08h 15m",
        "location": "DC-Paris-01",
        "cores": 32,
        "ramTotal": 128,
        "lastChecked": "1 min ago",
    },
    {
        "id": "srv-003",
        "name": "RAXUS-DB-01",
        "ip": "10.0.2.10",
        "type": "oracle",
        "os": "Oracle Linux 8.6",
        "status": "online",
        "cpu": 55,
        "memory": 75,
        "disk": 72,
        "uptime": "90d 03h 45m",
        "location": "DC-Lyon-01",
        "cores": 48,
        "ramTotal": 256,
        "lastChecked": "30 sec ago",
    },
    {
        "id": "srv-004",
        "name": "RAXUS-WIN-01",
        "ip": "10.0.3.10",
        "type": "windows",
        "os": "Windows Server 2022",
        "status": "warning",
        "cpu": 91,
        "memory": 88,
        "disk": 82,
        "uptime": "15d 22h 10m",
        "location": "DC-Paris-02",
        "cores": 8,
        "ramTotal": 32,
        "lastChecked": "5 min ago",
    },
    {
        "id": "srv-005",
        "name": "RAXUS-BACKUP-01",
        "ip": "10.0.4.10",
        "type": "linux",
        "os": "Debian 12",
        "status": "online",
        "cpu": 12,
        "memory": 35,
        "disk": 68,
        "uptime": "120d 15h 00m",
        "location": "DC-Lyon-01",
        "cores": 8,
        "ramTotal": 32,
        "lastChecked": "Never",
    },
]